apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promotion-frontend
  namespace: craftista
spec:
  vars:
    - name: image
      value: docker.io/hardsontessi/microservice-frontend
    - name: repoURL
      value: https://github.com/hardsontsi/microservice-helmcharts.git
    - name: branch
      value: main
    - name: envPath
    - name: argocdApp
  steps:
    - uses: git-clone
      config:
        repoURL: ${{ vars.repoURL }}
        checkout:
          - branch: ${{ vars.branch }}
            path: ./out

    - uses: yaml-update
      as: update-image
      config:
        path: ./out/${{ vars.envPath }}/frontend-values.yaml
        updates:
          - key: image.tag
            value: ${{ imageFrom( vars.image ).Tag }}

    - uses: git-commit
      as: commit
      config:
        path: ./out
        message: ${{ task.outputs['update-image'].commitMessage }}

    - uses: git-push
      as: push
      config:
        path: ./out
        generateTargetBranch: true

    - uses: git-open-pr
      as: open-pr
      config:
        repoURL: ${{ vars.repoURL }}
        sourceBranch: ${{ outputs.push.branch }}
        targetBranch: ${{ vars.branch }}

    - uses: git-wait-for-pr
      as: wait-for-pr
      config:
        repoURL: ${{ vars.repoURL }}
        prNumber: ${{ outputs['open-pr'].id }}

    - uses: argocd-update
      config:
        apps:
          - name: ${{ vars.argocdApp }}
            namespace: argocd
