apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

  # - catalogue/catalogue-values.yaml
  # - catalogue-db/catalogue-db-values.yaml
  # - recommendation/recommendation-values.yaml
resources:
- frontend/frontend-values.yaml
- voting/voting-values.yaml

labels:
- includeSelectors: true
  pairs:
    environment: staging
    managed-by: kustomize
